#!/usr/bin/env bash
# config.sh — TOML configuration generation for server, client, and permissions.
#
# Sourced by setup.sh; do not execute directly.
# Requires: common.sh (for toml_escape, toml_key, DEFAULT_DATA_DIR)
# Expects from caller: INSTALL_MODE, IRC_SERVER_PASS, IRC_SERVER_PASS_TOML,
#   LLM_PROVIDER_ID, LLM_API_BASE, LLM_MODEL, ADMIN_NICK_TOML, ADMIN_NICK_KEY,
#   BUS_KEY, VAULT_PASS, DASHBOARD_ENABLED, DASHBOARD_PORT, SEARCH_PROVIDER,
#   TOOL_SHELL, TOOL_CODE_EXEC, TOOL_RSS, TOOL_DNS, TOOL_HTTP,
#   TOOL_IRC_MANAGE, TOOL_CONFIG_MANAGE, TOOL_SYSTEMINFO, TOOL_SEARXNG,
#   TOOL_BROWSER, TOOL_OPENCODE, OPER_PASS, OPENCODE_API_KEY,
#   RAG_ENABLED, SUMMARY_MODEL (for server config)
# Additional for client: CLIENT_ID, CLIENT_HOSTNAME, CLIENT_AUTONOMY,
#   IRC_PASSWORD_TOML, CLIENT_NICK_SAFE, BUS_KEY_TOML, VAULT_ENABLED,
#   CT_* flags, API_ENABLED (for standalone client config)

# ─── Generate server config ─────────────────────────────────────────────────

generate_server_config() {
	local irc_server irc_port irc_tls data_dir config_path vault_db_path memory_db_path
	local system_prompt_path permissions_path

	if [[ "$INSTALL_MODE" == "docker" ]]; then
		irc_server="ircd"
		irc_port="6667"
		irc_tls="false"
		data_dir="/data"
		config_path="/etc/murmur/server.toml"
		vault_db_path="/data/vault.db"
		memory_db_path="/data/memory.db"
		system_prompt_path="/data/system_prompt.md"
		permissions_path="/data/permissions.toml"
	else
		irc_server="localhost"
		irc_port="6667"
		irc_tls="false"
		data_dir="$DEFAULT_DATA_DIR"
		config_path="$DEFAULT_DATA_DIR/server.toml"
		vault_db_path="$DEFAULT_DATA_DIR/vault.db"
		memory_db_path="$DEFAULT_DATA_DIR/memory.db"
		system_prompt_path="$DEFAULT_DATA_DIR/system_prompt.md"
		permissions_path="$DEFAULT_DATA_DIR/permissions.toml"
	fi

	local irc_password_line=""
	if [[ -n "$IRC_SERVER_PASS" ]]; then
		irc_password_line="password = \"$IRC_SERVER_PASS_TOML\""
	else
		irc_password_line="# password = \"\""
	fi

	# Build OPER config lines
	local oper_lines=""
	if [[ -n "${OPER_PASS:-}" ]]; then
		oper_lines="oper_user = \"admin\"
oper_password = \"vault:oper-password\""
	else
		oper_lines="# oper_user = \"admin\"
# oper_password = \"vault:oper-password\""
	fi

	cat <<TOML
# Murmur server configuration — generated by setup wizard

[server]
data_dir = "$data_dir"
system_prompt_file = "$system_prompt_path"
name = "server"
verbose = true

[irc]
server = "$irc_server"
port = $irc_port
tls = $irc_tls
nick = "murmur"
user = "murmur"
realname = "Murmur Agent"
$irc_password_line
nickserv_password = "vault:nickserv-password"
$oper_lines
max_line_len = 8192

[irc.channels]
main = "#murmur"
bus = "#murmur-bus"

[llm]
default = "$LLM_PROVIDER_ID"

[llm.providers.$LLM_PROVIDER_ID]
api_base = "$LLM_API_BASE"
api_key = "vault:llm-api-key"
model = "$(toml_escape "$LLM_MODEL")"
max_tokens = 8192
temperature = 0.7

[memory]
db_path = "$memory_db_path"
max_history = 100
TOML

	# Summary model (optional)
	if [[ -n "${SUMMARY_MODEL:-}" ]]; then
		cat <<TOML
summary_model = "$(toml_escape "$SUMMARY_MODEL")"
TOML
	fi

	# RAG memory search
	if [[ "${RAG_ENABLED:-false}" == "true" ]]; then
		cat <<'TOML'

[memory.rag]
enabled = true
auto_ingest_summaries = true
TOML
	fi

	cat <<TOML

[scheduler]
enabled = true
heartbeat_interval = "5m"
client_timeout = "2m"
tick_interval = "30s"
max_concurrent = 3

[security]
allowed_users = ["$ADMIN_NICK_TOML"]
require_nickserv = true
bus_key = "$BUS_KEY"
permissions_file = "$permissions_path"

[vault]
enabled = true
db_path = "$vault_db_path"
passphrase_env = "MURMUR_VAULT_PASS"
TOML

	# Server-side tools
	if [[ "$TOOL_SHELL" == "true" ]]; then
		if [[ "$INSTALL_MODE" == "docker" ]]; then
			cat <<'TOML'

[tools.shell]
enabled = true
docker_image = "murmur-shell:latest"
network = true
memory_limit = "256m"
cpu_limit = "1.0"
timeout = "60s"
TOML
		else
			cat <<'TOML'

[tools.shell]
enabled = true
docker_image = "ubuntu:24.04"
network = false
memory_limit = "256m"
cpu_limit = "0.5"
timeout = "30s"
TOML
		fi
	fi

	if [[ "$TOOL_CODE_EXEC" == "true" ]]; then
		local piston_url
		if [[ "$INSTALL_MODE" == "docker" ]]; then
			piston_url="http://piston:2000"
		else
			piston_url="http://localhost:2000"
		fi
		cat <<TOML

[tools.code_exec]
enabled = true
piston_url = "$piston_url"
default_language = "python"
TOML
	fi

	if [[ "$TOOL_RSS" == "true" ]]; then
		cat <<'TOML'

[tools.rss]
enabled = true
max_items = 10
TOML
	fi

	if [[ "$TOOL_DNS" == "true" ]]; then
		cat <<'TOML'

[tools.dns]
enabled = true
TOML
	fi

	if [[ "$TOOL_HTTP" == "true" ]]; then
		cat <<'TOML'

[tools.http]
enabled = true
timeout = "30s"
max_response_bytes = 1048576
block_private_ips = true
TOML
	fi

	if [[ "${TOOL_SYSTEMINFO:-false}" == "true" ]]; then
		cat <<'TOML'

[tools.systeminfo]
enabled = true
TOML
	fi

	if [[ "${TOOL_SEARXNG:-false}" == "true" || "$SEARCH_PROVIDER" == "searxng" ]]; then
		local searxng_url
		if [[ "$INSTALL_MODE" == "docker" ]]; then
			searxng_url="http://searxng:8080"
		else
			searxng_url="http://localhost:8080"
		fi
		cat <<TOML

[tools.searxng]
enabled = true
url = "$searxng_url"
max_results = 10
TOML
	elif [[ "$SEARCH_PROVIDER" == "brave" ]]; then
		cat <<'TOML'

[tools.web_search]
enabled = true
api_key = "vault:brave-search-key"
max_results = 5
TOML
	fi

	if [[ "${TOOL_BROWSER:-false}" == "true" ]]; then
		local browser_endpoint
		if [[ "$INSTALL_MODE" == "docker" ]]; then
			browser_endpoint="http://browser:3001"
		else
			browser_endpoint="http://localhost:3001"
		fi
		cat <<TOML

[tools.browser]
enabled = true
endpoint = "$browser_endpoint"
TOML
	fi

	if [[ "${TOOL_OPENCODE:-false}" == "true" ]]; then
		local opencode_url
		if [[ "$INSTALL_MODE" == "docker" ]]; then
			opencode_url="http://opencode:3000"
		else
			opencode_url="http://localhost:3000"
		fi
		cat <<TOML

[tools.opencode]
enabled = true
url = "$opencode_url"
TOML
	fi

	if [[ "$TOOL_CONFIG_MANAGE" == "true" ]]; then
		cat <<TOML

[tools.config_manage]
enabled = true
config_path = "$config_path"
TOML
	fi

	if [[ "$TOOL_IRC_MANAGE" == "true" ]]; then
		cat <<'TOML'

[tools.irc_manage]
enabled = true
TOML
	fi

	# API
	cat <<TOML

[api]
enabled = true
listen = "0.0.0.0:8080"
api_key = "vault:api-key"
event_retention_days = 30
TOML

	# Dashboard
	if [[ "$DASHBOARD_ENABLED" == "true" ]]; then
		cat <<TOML

[dashboard]
enabled = true
listen = "0.0.0.0:$DASHBOARD_PORT"
TOML
		# Auto-populate server_password so dashboard users don't need to know it
		if [[ -n "$IRC_SERVER_PASS" ]]; then
			cat <<'TOML'
server_password = "vault:irc-server-password"
TOML
		fi
	fi

	# Debug (commented out)
	cat <<'TOML'

# [debug]
# enabled = true
# channel = "#murmur-debug"
# log_level = "debug"
# log_tool_calls = true
# log_llm_requests = true
# log_permissions = true
TOML
}

# ─── Generate client config (co-located with server) ────────────────────────

generate_client_config() {
	local irc_server irc_port irc_tls vault_db_path

	if [[ "$INSTALL_MODE" == "docker" ]]; then
		irc_server="ircd"
		irc_port="6667"
		irc_tls="false"
		vault_db_path="/data/vault.db"
	else
		irc_server="localhost"
		irc_port="6667"
		irc_tls="false"
		vault_db_path="$DEFAULT_DATA_DIR/vault.db"
	fi

	local irc_password_line=""
	if [[ -n "$IRC_SERVER_PASS" ]]; then
		irc_password_line="password = \"$IRC_SERVER_PASS_TOML\""
	else
		irc_password_line="# password = \"\""
	fi

	cat <<TOML
# Murmur client configuration — generated by setup wizard

[client]
id = "local"
hostname = "$(hostname -s 2>/dev/null || echo "murmur-client")"
autonomy = "auto"

[irc]
server = "$irc_server"
port = $irc_port
tls = $irc_tls
nick = "murmur-client"
user = "murmur-client"
realname = "Murmur Client"
$irc_password_line
nickserv_password = "vault:client-nickserv-password"
bus_channel = "#murmur-bus"
max_line_len = 8192

[heartbeat]
interval = "30s"

[security]
bus_key = "$BUS_KEY"

[vault]
enabled = true
db_path = "$vault_db_path"
passphrase_env = "MURMUR_VAULT_PASS"

[tools.systeminfo]
enabled = true
TOML

	if [[ "$TOOL_SHELL" == "true" ]]; then
		if [[ "$INSTALL_MODE" == "docker" ]]; then
			cat <<'TOML'

[tools.shell]
enabled = true
docker_image = "murmur-shell:latest"
network = true
memory_limit = "256m"
cpu_limit = "1.0"
timeout = "60s"
TOML
		else
			cat <<'TOML'

[tools.shell]
enabled = true
docker_image = "ubuntu:24.04"
network = false
memory_limit = "256m"
cpu_limit = "0.5"
timeout = "30s"
TOML
		fi
	fi

	# Client API
	if [[ "$INSTALL_MODE" == "docker" ]]; then
		cat <<'TOML'

[api]
enabled = true
listen = "0.0.0.0:8081"
api_key = "vault:api-key"
TOML
	fi
}

# ─── Generate standalone client config ───────────────────────────────────────

generate_standalone_client_config() {
	local irc_password_line=""
	if [[ -n "$IRC_PASSWORD" ]]; then
		irc_password_line="password = \"$IRC_PASSWORD_TOML\""
	else
		irc_password_line="# password = \"\""
	fi

	cat <<TOML
# Murmur client configuration — generated by setup wizard

[client]
id = "$(toml_escape "$CLIENT_ID")"
hostname = "$(toml_escape "$CLIENT_HOSTNAME")"
autonomy = "$CLIENT_AUTONOMY"

[irc]
server = "$(toml_escape "$IRC_SERVER")"
port = $IRC_PORT
tls = $IRC_TLS
nick = "$CLIENT_NICK_SAFE"
user = "$CLIENT_NICK_SAFE"
realname = "Murmur Client"
$irc_password_line
bus_channel = "#murmur-bus"
max_line_len = 8192

[heartbeat]
interval = "30s"

[security]
bus_key = "$BUS_KEY_TOML"
TOML

	if [[ "$VAULT_ENABLED" == "true" ]]; then
		cat <<TOML

[vault]
enabled = true
db_path = "$DEFAULT_DATA_DIR/vault.db"
passphrase_env = "MURMUR_VAULT_PASS"
TOML
	fi

	# Tools
	if [[ "$CT_SYSTEMINFO" == "true" ]]; then
		cat <<'TOML'

[tools.systeminfo]
enabled = true
TOML
	fi

	if [[ "$CT_SHELL" == "true" ]]; then
		cat <<'TOML'

[tools.shell]
enabled = true
docker_image = "ubuntu:24.04"
network = false
memory_limit = "256m"
cpu_limit = "0.5"
timeout = "30s"
TOML
	fi

	if [[ "$CT_CODE_EXEC" == "true" ]]; then
		cat <<'TOML'

[tools.code_exec]
enabled = true
piston_url = "http://localhost:2000"
default_language = "python"
TOML
	fi

	if [[ "$CT_MAIL_READ" == "true" ]]; then
		cat <<'TOML'

[tools.mail_read]
enabled = true
thunderbird_profile = "~/.thunderbird/CHANGEME.default-release" # TODO: set your Thunderbird profile path
mail_dir = "Mail/pop3.example.com" # TODO: set your mail directory
TOML
	fi

	if [[ "$CT_MAIL_SEND" == "true" ]]; then
		cat <<'TOML'

[tools.mail_send]
enabled = true
smtp_host = "smtp.example.com" # TODO: set your SMTP server
smtp_port = 587
smtp_user = "you@example.com" # TODO: set your email address
smtp_password = "vault:smtp-password" # TODO: store password in vault
from_address = "you@example.com" # TODO: set your from address
TOML
	fi

	if [[ "$CT_WEB_SEARCH" == "true" ]]; then
		cat <<'TOML'

[tools.web_search]
enabled = true
api_key = "vault:brave-search-key" # TODO: store Brave API key in vault
max_results = 5
TOML
	fi

	if [[ "$CT_RSS" == "true" ]]; then
		cat <<'TOML'

[tools.rss]
enabled = true
max_items = 10
TOML
	fi

	if [[ "$CT_DNS" == "true" ]]; then
		cat <<'TOML'

[tools.dns]
enabled = true
TOML
	fi

	if [[ "$CT_GIT" == "true" ]]; then
		cat <<'TOML'

[tools.git]
enabled = true
allowed_repos = [
    "/home/user/projects/myapp", # TODO: add your repo paths
]
TOML
	fi

	if [[ "$CT_FILE_OPS" == "true" ]]; then
		cat <<'TOML'

[tools.file_ops]
enabled = true
allowed_paths = [
    "/home/user/documents", # TODO: add your allowed paths
]
TOML
	fi

	if [[ "$CT_IMAGE_GEN" == "true" ]]; then
		cat <<'TOML'

[tools.image_gen]
enabled = true
comfyui_host = "http://localhost:8188" # TODO: set your ComfyUI URL
output_dir = "/home/user/images/murmur" # TODO: set output directory
checkpoint_name = "sd_xl_base_1.0.safetensors"
TOML
	fi

	if [[ "$CT_SEARXNG" == "true" ]]; then
		cat <<'TOML'

[tools.searxng]
enabled = true
url = "http://localhost:8080"
max_results = 10
TOML
	fi

	if [[ "$API_ENABLED" == "true" ]]; then
		cat <<'TOML'

[api]
enabled = true
listen = "0.0.0.0:8081"
api_key = "vault:api-key"
TOML
	fi
}

# ─── Generate permissions.toml ───────────────────────────────────────────────

generate_permissions_config() {
	cat <<TOML
# Murmur permissions — generated by setup wizard

[users.default]
role = "user"
tools = ["*"]
deny_tools = []
autonomy = "approve"
max_messages_per_hour = 60

[users.$ADMIN_NICK_KEY]
role = "admin"
tools = ["*"]
autonomy = "auto"
max_messages_per_hour = -1
TOML
}

# ─── Generate .env ───────────────────────────────────────────────────────────

generate_env_file() {
	local content="MURMUR_VAULT_PASS=$VAULT_PASS"
	content+=$'\n'
	if [[ "$DASHBOARD_ENABLED" == "true" ]]; then
		content+="MURMUR_DASHBOARD_PORT=$DASHBOARD_PORT"
		content+=$'\n'
	fi
	if [[ -n "${OPENCODE_API_KEY:-}" ]]; then
		content+="OPENROUTER_API_KEY=$OPENCODE_API_KEY"
		content+=$'\n'
	fi
	printf '%s' "$content"
}
